apiVersion: v2
name: watchtower
description: A basic observability stack for k8s 
type: application
version: 1.3.0
appVersion: "1.3.0"

dependencies:
# for aggregating pods logs & kube audit log
- name: promtail
  version: "6.15.5"
  repository: "https://grafana.github.io/helm-charts"

# data viz
- name: grafana
  version: "7.3.7"
  repository: "https://grafana.github.io/helm-charts"

# for node-level monitoring
- name: telegraf-ds
  version: "1.1.24"
  repository: "https://helm.influxdata.com/"
