apiVersion: v2
name: watchtower
description: A basic observability stack for k8s 
type: application
version: 0.6.0
appVersion: "1.0.0"

dependencies:
# for aggregating pods logs & kube audit log
- name: promtail
  version: "6.11.0"
  repository: "https://grafana.github.io/helm-charts"

# data viz
- name: grafana
  version: "6.56.0"
  repository: "https://grafana.github.io/helm-charts"

# for node-level monitoring
- name: telegraf-ds
  version: "1.1.9"
  repository: "https://helm.influxdata.com/"
