apiVersion: v2
name: watchtower
description: A basic observability stack for k8s 
type: application
version: 0.3.0
appVersion: "1.0.0"

dependencies:
# for aggregatinh pods logs & kube audit log
- name: promtail
  version: "6.10.0"
  repository: "https://grafana.github.io/helm-charts"

# data viz
- name: grafana
  version: "6.54.0"
  repository: "https://grafana.github.io/helm-charts"

# for node-level & kubernetes metrics
- name: telegraf-ds
  version: "1.1.9"
  repository: "https://helm.influxdata.com/"
