# where on the host is the audit log file ?
audit_log:
  host_file: &audit_log_file "/var/log/kubernetes/kube-apiserver-audit.log"


# subcharts configuration
# should not be necessary to change anyhing below unless you have a very specific setup 
grafana:
  service:
    port: 3000
  image:
    tag: 10.4.0
  persistence:
    enabled: true
    size: 100Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        uid: lokids1
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          maxLines: 1000
      - name: InfluxDB
        type: influxdb
        uid: influxds1
        access: proxy
        url: http://influxdb:8086
        editable: true
        jsonData:
          dbName: metrics
          httpMode: GET
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      audit:
        url: https://raw.githubusercontent.com/k0rventen/k8s-watchtower/main/dashboards/audit_dashboard.json
      host:
        url: https://raw.githubusercontent.com/k0rventen/k8s-watchtower/main/dashboards/hosts_metrics.json
      apps:
        url: https://raw.githubusercontent.com/k0rventen/k8s-watchtower/main/dashboards/workloads_dashboard.json

telegraf-ds:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  config:
    docker_endpoint: ""
  override_config:
    toml: |
      [agent]
        hostname = "$HOSTNAME"
        interval = "30s"

      [[outputs.influxdb]]
        urls = ["http://influxdb:8086"]
        database = "metrics"

      [[inputs.cpu]]
        percpu = true
        totalcpu = true
      [[inputs.disk]]
        ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
      [[inputs.diskio]]
       devices = ["sda"]
      [[inputs.mem]]
      [[inputs.processes]]
      [[inputs.system]]
      [[inputs.net]]
        interfaces = ["eth*","ens*"]
      [[inputs.kubernetes]]
        url = "https://$HOSTIP:10250"
        insecure_skip_verify = true

promtail:
  extraVolumeMounts:
  - mountPath: /log/kube-apiserver-audit.log
    name: host-audit-logs
  extraVolumes:
  - name: host-audit-logs
    hostPath:
      path: *audit_log_file
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    snippets:
      extraScrapeConfigs: |
        - job_name: kube-audit
          pipeline_stages:
          - json:
              expressions:
                verb: verb
                objectRef:
                user:
                annotations:
          - json:
              expressions:
                namespace:
              source: objectRef
          - json:
              expressions:
                resource:
              source: objectRef
          - json:
              expressions:
                name:
              source: objectRef
          - json:
              expressions:
                username:
              source: user 
          - json:
              expressions:
                decision: '"authorization.k8s.io/decision"'
              source: annotations
          - labels:
              decision:
              username:
              namespace:
              resource:
              verb:
              resource_name: name
          static_configs:
          - targets:
              - localhost
            labels:
              job: kube-audit
              __path__: /log/kube-apiserver-audit.log