apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influx
        image: influxdb:1.8-alpine
        resources: {}
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: "/var/lib/influxdb"
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-influxdb-data
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: influxdb
  ports:
  - port: 8086
    targetPort: 8086
    name: influx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-influxdb-data
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
