{
 "title": "k8s audit dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "username",
    "query": {}
   },
   {
    "name": "verb",
    "query": {}
   },
   {
    "name": "resource",
    "query": {}
   },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "$namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "namespace" },
  {
   "title": "Requests per user",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(username) (count_over_time({filename=\"/log/kube-apiserver-audit.log\", namespace=~\"$namespace\"} | json | username !~ `system:serviceaccount:kube-system.*|system:node.*` [$__range])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(namespace) (count_over_time({filename=\"/log/kube-apiserver-audit.log\", namespace=~\"$namespace\"} | json [1m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Forbidden requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/log/kube-apiserver-audit.log\", namespace=~\"$namespace\"} | json | annotations_authorization_k8s_io_decision = `forbid` [5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "Delete commands",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/log/kube-apiserver-audit.log\", namespace=~\"$namespace\"} | json | verb = `delete` [5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "Execs commands",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/log/kube-apiserver-audit.log\", namespace=~\"$namespace\"} | json | objectRef_subresource = `exec` [5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "configmaps updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/log/kube-apiserver-audit.log\", resource=\"configmaps\", verb=~\"update|create|delete\", namespace=~\"$namespace\"} | json [5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "secrets updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"/log/kube-apiserver-audit.log\", resource=\"secrets\", verb=~\"update|create|delete\", namespace=~\"$namespace\"} | json [5m]))",
     "legendFormat": "curl/requests"
    }
   ]
  },
  {
   "title": "Latest logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/log/kube-apiserver-audit.log\", namespace=~\"$namespace\", username=~\"$username\", verb=~\"$verb\", resource=~\"$resource\"} |= `$search` | json | line_format `{{ .username }} {{ .verb }} on {{.resource}}/{{.resource_name}} `",
     "maxLines": 40
    }
   ]
  },
  {
   "title": "Latest error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/log/kube-apiserver-audit.log\"} | json | decision != `allow` | line_format `{{ .username }} ({{.impersonatedUser_username}}) {{ .verb }} on {{.resource}}/{{.resource_name}}  -> {{.responseStatus_message}}`",
     "maxLines": 40
    }
   ]
  }
 ]
}