apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-loki
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:main
        args:
        - -config.file=/etc/loki/local-config.yaml
        - -querier.parallelise-shardable-queries=false
        - -reporting.enabled=false
        resources: {}
        ports:
        - containerPort: 3100
        volumeMounts:
        - mountPath: "/loki"
          name: loki-storage
      volumes:
      - name: loki-storage
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-loki-data
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-loki-data
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
