name: Release Charts

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
      - name: Update helm subcharts
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add influx https://helm.influxdata.com/ 
          
          helm dependency update watchtower/
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: ./
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"