name: Release Chart

permissions:
  contents: write
  
on:
  push:
    tags:
    - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: install helm
        uses: Azure/setup-helm@v3
      
      - name: helm linting
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add influx https://helm.influxdata.com/ 
          helm dependency update watchtower/
          helm lint --strict watchtower/

      - name: create test cluster
        uses: helm/kind-action@v1.4.0
        with:
          config: ./kind/kind-config.yaml

      - name: install watchtower
        run: |
          helm upgrade --wait --install --namespace watchtower --create-namespace watchtower watchtower/ 
          kubectl get all -n watchtower

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

      - name: run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: ./
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"


      - name: Update Release notes
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
